### ISSUE TITLE
Call the queue with different options

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web-server#31]
I'm looking for a way to call the queue with different options in GraphQL so that I can do https://github.com/taskcluster/taskcluster-tools/blob/2d2897bd5e8cab418fbfd518dbcc9c892abfa066/src/views/UnifiedInspector/ActionsMenu.jsx#L471-L473.

**Comment by eliperelman** [comment]
Maybe add more options to `TaskInput`? https://github.com/taskcluster/taskcluster-web-server/blob/master/src/graphql/Tasks.graphql#L169

**Comment by helfi92** [comment]
I think that'll work. Thanks @eliperelman 🙌
