### ISSUE TITLE
Rename a task's taskGroup to decisionTask

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web-server#75]
Rename https://github.com/taskcluster/taskcluster-web-server/blob/5ad463e6044f3eb869b8adc7bb46dd69afe06f6f/src/graphql/Tasks.graphql#L160 to `decisionTask`:

```graphql
decisionTask: Task
```

Given that taskcluster-web is the only consumer of taskcluster-web-server, this renaming should be okay but we should make sure the change is implemented in taskcluster-web as well.

**Comment by knrt10** [comment]
@helfi92 I would like to work on this.
